# bundle_id = "domain.id"
# path is the relative path to the workflow in the project root
---
path: src
domain: patout.berlin
id: alfred2-jenkins-workflow
# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: "~/Google Drive/Dev files/alfred"